/****************************************************************
*@Program: xrtdb -> Cambada soccer robots configuration files	*
*		automatic generator				*
*@Authors: Tiago Nunes Mec 37161				*
*	   Milton Gregório Mec 36275				*
*	   David Ferreira Mec 36129				*
*@Year: 2007							*
*@Univ: Universidade de Aveiro					*
*@File: rtdb_configuration.h 					*
*@Description: Headerfile with global configurations options	*
*****************************************************************/
#ifndef _RTDB_CONFIGURATION_H
#define _RTDB_CONFIGURATION_H

//Define if in the sizeof(datatype), the datatype should be prefixed with struct, to be sizeof(struct datatype) 
#define STRUCTPREFIX ""
//System command to remove files
#define RM_COMMAND "/bin/rm -f"
//Compiler used to compile the rtdb_sizeof_tmp.c file generated by getSizeOf()
#define CC "g++"
//Command to view the files written by getSizeof() if in Debug Sizeof mode 
#define TXTVIEWER "cat"
//If in Debug mode the program outputs many information concerning what's doing
#define DEBUG 1
/*
There's an optional debug mode concerning the getSizeOf() function, because it creates
many files, compiles and executes them, and if DebugSizeOf mode is activated
the user is prompted what to do after after each action of the getSizeOf() function
*/
#define DEBUGSIZEOF 0
//If in DebugSizeOf mode, set CFLAGS to show all warnings and include debugging info in the compiled files
#if DEBUGSIZEOF
//Compilation flags to use to compile the rtdb_sizeof_tmp.c file if in DebugSizeOf mode
#define CFLAGS "-Wall -g -I../ -I../include/ -I../worldmodel"
#else
//Compilation flags to use to compile the rtdb_sizeof_tmp.c file if in user mode
#define CFLAGS "-Wall -I../ -I../include/ -I../worldmodel"
#endif
//Function to clean the stdin after scanning a character
#define purge() \
	{ \
	scanf("%*[^\n]"); \
	scanf("%*c"); \
	}

#endif

//Default files
#define RTDB_CONF "../config/rtdb.conf"
#define RTDB_INI "../config/rtdb.ini"
#define RTDB_USER_H "../rtdb/rtdb_user.h"
#define RTDB_NETWORK_H "../rtdb/rtdb_network.h"

/* EOF: rtdb_configuration.h */
